In [1]:
import numpy as np

In [5]:
np.random.random()

0.9345113692221186

In [22]:
# Same random will genrate again and again 



np.random.random()

0.9476322568516703

In [31]:
#np.random.seed(200)
np.random.uniform(2,3)

2.94763225685167

In [35]:
np.random.uniform(1,100,10).reshape(2,5)

array([[76.11134086, 68.28454159, 33.60546228,  3.61903343, 80.56237822],
       [97.31008978, 29.01087336, 65.25839263, 27.29193488, 19.58122506]])

In [37]:
np.random.randint(1,5,6).reshape(2,3)

array([[1, 3, 4],
       [2, 3, 2]])

In [40]:
a=np.random.randint(1,10,6)
a

array([2, 8, 1, 3, 7, 6])

In [42]:
a.max()

8

In [44]:
np.max(a)
np.min(a)

1

In [46]:
a[np.argmax(a)]

8

In [47]:
a[np.argmin(a)]

1

In [48]:
a=np.random.randint(1,10,6)
a

array([2, 2, 2, 9, 4, 1])

In [50]:
a[a%2==1]=-1
a

array([ 2,  2,  2, -1,  4, -1])

In [51]:
np.where(a%2==1,-1,a)

array([ 2,  2,  2, -1,  4, -1])

In [56]:
b=np.random.randint(1,50,10)
b

array([ 2, 32, 21, 34, 45, 22, 13, 43, 46, 16])

In [55]:
c=np.sort(b)
c

array([ 8, 24, 26, 28, 30, 33, 37, 39, 44, 47])

In [57]:
np.percentile(b,25)

17.25

In [58]:
np.percentile(b,50)

27.0

In [59]:
np.percentile(b,100)

46.0